spring.application.name=EduHub-BackEnd
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
server.port=8081
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/edu_hub_hibernate
spring.datasource.username=postgres
spring.datasource.password=Dariociaodarwin125

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.file.name=logs/app.log